language: c
addons:
  apt:
    sources:
      - avsm
    packages:
      - ocaml
      - opam
      - aspcud
env:
  - MODE=build
  - MODE=aggregation-test
  - MODE=aggregation-dynamic-test
script: bash -ex .travis-ci.sh
sudo: false
notifications:
  email: false
