language: c
addons:
  apt:
    sources:
      - avsm
    packages:
      - ocaml
      - opam
      - aspcud
      - portaudio19-dev
env:
  global:
    - COQ_VERSION=8.5.3
    - SSREFLECT_VERSION=1.6
    - AAC_TACTICS_VERSION=8.5.1
  matrix:
    - MODE=build
    - MODE=aggregation-test
    - MODE=aggregation-dynamic-test
    - MODE=analytics
before_install:
  - openssl aes-256-cbc -K $encrypted_80476f3400be_key -iv $encrypted_80476f3400be_iv -in .travis/travis_rsa.enc -out .travis/travis_rsa -d
  - cp .travis/travis_rsa ~/.ssh
  - chmod 600 ~/.ssh/travis_rsa
  - cp .travis/ssh_config ~/.ssh/config
script: bash -ex .travis-ci.sh
sudo: false
notifications:
  email: false
