language: c
addons:
  apt:
    sources:
      - avsm
    packages:
      - ocaml
      - opam
      - aspcud
env:
  global:
    - COQ_VERSION=8.5.3
    - MATHCOMP_VERSION=1.6
  matrix:
    - MODE=build
    - MODE=aggregation-test
    - MODE=aggregation-dynamic-test
script: bash -ex .travis-ci.sh
sudo: false
notifications:
  email: false
